import { type NextRequest, NextResponse } from "next/server"

export async function POST(req: NextRequest) {
  try {
    const { method, contact, farmDetails, recommendation } = await req.json()

    // Format the recommendation message
    const message = `WELAND FARM ASSISTANT - PERSONALIZED RECOMMENDATIONS

Farm Details:
📍 Location: ${farmDetails.location}
🌾 Crop: ${farmDetails.cropType}
📏 Size: ${farmDetails.farmSize}
🌱 Soil: ${farmDetails.soilDescription || "Not specified"}

RECOMMENDATIONS:
${recommendation}

---
Generated by Weland Farm Assistant
Contact us: +254 710 546 911
Website: weland-farm-assistant.vercel.app`

    if (method === "whatsapp") {
      // For WhatsApp, we'll create a link that opens WhatsApp with the message
      // In a real implementation, you might use WhatsApp Business API
      const encodedMessage = encodeURIComponent(`Hello! Here are your farm recommendations:\n\n${message}`)
      const whatsappUrl = `https://wa.me/${contact.replace(/[^0-9]/g, "")}?text=${encodedMessage}`

      // For now, we'll just log this. In production, you'd use WhatsApp Business API
      console.log("WhatsApp message would be sent to:", contact)
      console.log("Message:", message)

      return NextResponse.json({
        success: true,
        message: "WhatsApp message prepared",
        url: whatsappUrl,
      })
    }

    if (method === "sms") {
      // For SMS, you'd integrate with an SMS service like Twilio, Africa's Talking, etc.
      // For now, we'll simulate the SMS sending
      console.log("SMS would be sent to:", contact)
      console.log("Message:", message.substring(0, 160) + "...") // SMS character limit

      return NextResponse.json({
        success: true,
        message: "SMS sent successfully",
      })
    }

    if (method === "email") {
      // For email, you'd integrate with an email service like SendGrid, Resend, etc.
      // For now, we'll simulate the email sending
      console.log("Email would be sent to:", contact)
      console.log("Subject: Your Farm Recommendations from Weland")
      console.log("Body:", message)

      return NextResponse.json({
        success: true,
        message: "Email sent successfully",
      })
    }

    return NextResponse.json({ error: "Invalid sharing method" }, { status: 400 })
  } catch (error) {
    console.error("Error sharing recommendation:", error)
    return NextResponse.json({ error: "Failed to share recommendation" }, { status: 500 })
  }
}
